#cloud-config

#packages: [ make ]

# Capture all subprocess output into a logfile
# Useful for troubleshooting cloud-init issues
output: {all: '| tee -a /var/log/cloud-init-output.log'} 

# TODO: remove before publishing
#ssh_authorized_keys:
#  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYU+u7FKdFoRq2BFyAVVznMhGmI4IiaqS3ewqpaaoSzMYoQ0UyUI7OOYHxDM1QI9E8ubX/j9+UJQFbGquT8cOO2pBqsjNQtumqzKgehzoDhjKomEC0KgqrCUjCA7JaLx5F+Lo1D8Vjco4K0CC1fjy6Lm8gbZxNC0D77xgyL2mmBbXO+LTm/CE+AmsHXh8OnLRzUVFdoOZYDJpCS7FlQixYhhd08nPjUqa9aAhpyURBwxLFojtdBFK/5lgOPlZBq0JSCn3lAPdrrZCA3zw6cs5AoPy3keOffbqoMs+/r9QqTPUrkfkt5AqPOXZaFkt3Xkaz53Tb6y696KiPr+2U1gSkuVnjxUUTXzukYGa6/r/CB6E7m8d70Sw1j3QGC1diohyEnYYuOWYv39GsOmfjjA0pTGwi3OiB5dWD1REfY6dJXbf2gamuULwy8q/C26fFNuTilg1JlBuxK8PzeWTuSCoeWdhXna1Z8BWQ4b55oV8puJeBiAl4NMgZ1k4vKGT4kBzMdhptYxHEt3IvnK7w/vzioLwBnhqORtiLheIsLCLKc2dWRDxbFq5540OiogqQMPYNOVboFxpbd5l0Z3mknULlmEXumgecg8UTwK4TE4eZkohhKEGG7EX65YqJOeQuKPSZjKC319Zs7h2fc6qS9tQO2M8/o6cQ2IYkTdVTyjz3OQ== gabriel@delta.local
