apiVersion: batch/v1
kind: Job
metadata:
  name: {{ randNumeric 12 | printf "%s-%s" "deis-upgrade"}}
  labels:
    heritage: deis
  annotations:
    "helm.sh/hook": post-upgrade
spec:
  template:
    spec:
      containers:
      - name: deis-upgrade
        image: quay.io/deis/workflow-upgrade:canary
        imagePullPolicy: Always
      restartPolicy: Never
