language: python
python: "3.5"
cache:
  directories:
    - $HOME/.local
    - $HOME/.cache/pip
services:
  - docker
env:
  - DOCKER_BUILD_FLAGS="--pull --no-cache"
install:
  - make deps
script:
  - make build docker-build test
